name: MiniBackpackPlugin
version: '1.1'
main: me.elaineqheart.miniBackpackPlugin.MiniBackpackPlugin
api-version: '1.21'
authors: [ ElaineQheart ]
website: https://www.youtube.com/@elaineqheart
commands:
  backpackitems:
    description: gives the backpack items
    permission: MiniBackpackPlugin.give
  editbackpack:
    description: opens the backpack editor
    permission: MiniBackpackPlugin.edit
  backpackreload:
    description: reloads the plugin if there were any changes in the config.yml file
    permission: MiniBackpackPlugin.edit